// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calcSize
int calcSize(NumericVector col, NumericVector fam);
RcppExport SEXP NAM_calcSize(SEXP colSEXP, SEXP famSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type col(colSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type fam(famSEXP );
        int __result = calcSize(col, fam);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// funI
NumericVector funI(NumericVector col, int fam, int finsiz, int f);
RcppExport SEXP NAM_funI(SEXP colSEXP, SEXP famSEXP, SEXP finsizSEXP, SEXP fSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type col(colSEXP );
        Rcpp::traits::input_parameter< int >::type fam(famSEXP );
        Rcpp::traits::input_parameter< int >::type finsiz(finsizSEXP );
        Rcpp::traits::input_parameter< int >::type f(fSEXP );
        NumericVector __result = funI(col, fam, finsiz, f);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// funX
NumericVector funX(NumericVector col, int finsiz);
RcppExport SEXP NAM_funX(SEXP colSEXP, SEXP finsizSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type col(colSEXP );
        Rcpp::traits::input_parameter< int >::type finsiz(finsizSEXP );
        NumericVector __result = funX(col, finsiz);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// inputRow
NumericVector inputRow(NumericVector x, int exp, int n);
RcppExport SEXP NAM_inputRow(SEXP xSEXP, SEXP expSEXP, SEXP nSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type exp(expSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        NumericVector __result = inputRow(x, exp, n);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// timesMatrix
NumericMatrix timesMatrix(NumericMatrix ma1, NumericVector h, NumericMatrix ma2, int rows, int cols);
RcppExport SEXP NAM_timesMatrix(SEXP ma1SEXP, SEXP hSEXP, SEXP ma2SEXP, SEXP rowsSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type ma1(ma1SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type ma2(ma2SEXP );
        Rcpp::traits::input_parameter< int >::type rows(rowsSEXP );
        Rcpp::traits::input_parameter< int >::type cols(colsSEXP );
        NumericMatrix __result = timesMatrix(ma1, h, ma2, rows, cols);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// timesVec
NumericMatrix timesVec(NumericVector aa, NumericVector h, NumericMatrix bb, int q);
RcppExport SEXP NAM_timesVec(SEXP aaSEXP, SEXP hSEXP, SEXP bbSEXP, SEXP qSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type aa(aaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type bb(bbSEXP );
        Rcpp::traits::input_parameter< int >::type q(qSEXP );
        NumericMatrix __result = timesVec(aa, h, bb, q);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
