# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcSize <- function(col, fam) {
    .Call('NAM_calcSize', PACKAGE = 'NAM', col, fam)
}

emBA <- function(y, gen, df = 5, R2 = 0.5, it = 75L) {
    .Call('NAM_emBA', PACKAGE = 'NAM', y, gen, df, R2, it)
}

emBB <- function(y, gen, df = 5, R2 = 0.5, it = 75L, Pi = 0.95) {
    .Call('NAM_emBB', PACKAGE = 'NAM', y, gen, df, R2, it, Pi)
}

emBC <- function(y, gen, df = 5, R2 = 0.5, it = 75L, Pi = 0.95) {
    .Call('NAM_emBC', PACKAGE = 'NAM', y, gen, df, R2, it, Pi)
}

emBL <- function(y, gen, it = 200L, R2 = 0.5, alpha = 0.025) {
    .Call('NAM_emBL', PACKAGE = 'NAM', y, gen, it, R2, alpha)
}

emRR <- function(y, gen, df = 5, R2 = 0.5, it = 75L) {
    .Call('NAM_emRR', PACKAGE = 'NAM', y, gen, df, R2, it)
}

funI <- function(col, fam, finsiz, f) {
    .Call('NAM_funI', PACKAGE = 'NAM', col, fam, finsiz, f)
}

funX <- function(col, finsiz) {
    .Call('NAM_funX', PACKAGE = 'NAM', col, finsiz)
}

gs <- function(C, g, r, N) {
    invisible(.Call('NAM_gs', PACKAGE = 'NAM', C, g, r, N))
}

inputRow <- function(x, exp, n) {
    .Call('NAM_inputRow', PACKAGE = 'NAM', x, exp, n)
}

KMUP <- function(X, b, d, xx, E, L, Ve, pi) {
    .Call('NAM_KMUP', PACKAGE = 'NAM', X, b, d, xx, E, L, Ve, pi)
}

KMUP2 <- function(X, Use, b, d, xx, E, L, Ve, pi) {
    .Call('NAM_KMUP2', PACKAGE = 'NAM', X, Use, b, d, xx, E, L, Ve, pi)
}

SAMP <- function(C, g, r, N, Ve) {
    invisible(.Call('NAM_SAMP', PACKAGE = 'NAM', C, g, r, N, Ve))
}

SAMP2 <- function(X, g, y, xx, E, L, N, Ve) {
    invisible(.Call('NAM_SAMP2', PACKAGE = 'NAM', X, g, y, xx, E, L, N, Ve))
}

timesMatrix <- function(ma1, h, ma2, rows, cols) {
    .Call('NAM_timesMatrix', PACKAGE = 'NAM', ma1, h, ma2, rows, cols)
}

timesVec <- function(aa, h, bb, q) {
    .Call('NAM_timesVec', PACKAGE = 'NAM', aa, h, bb, q)
}

